import React, { useState, useRef, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Loader2 } from 'lucide-react';
import shaka from 'shaka-player/dist/shaka-player.ui.js';
import 'shaka-player/dist/controls.css';

const PrimePlayer = ({ tmdbId, title, mediaType, season, episode }) => {
  const navigate = useNavigate();
  const videoRef = useRef(null);
  const containerRef = useRef(null);
  
  // -- State --
  const [isFetching, setIsFetching] = useState(true);
  const [error, setError] = useState(null);
  const [statusMsg, setStatusMsg] = useState("Locating stream via Streaming API...");
  const [playerInstance, setPlayerInstance] = useState(null);

  useEffect(() => {
    let isMounted = true;
    let player = null;
    let ui = null;

    const initializeStream = async () => {
      try {
        // 1. Request the manifest from your new internal Microservice API
        setStatusMsg("Requesting manifest from Streaming Service...");
        
        const apiUrl = `/api/streaming/get-stream?type=${mediaType}&id=${tmdbId}${mediaType === 'tv' ? `&season=${season}&episode=${episode}` : ''}`;
        
        const response = await fetch(apiUrl);
        const data = await response.json();

        if (!data.success) {
            // Handle cases where the backend is still transcoding or queued the task
            if (data.status === 'processing') {
                setStatusMsg("Content is currently being transcoded. Please wait...");
                // In a real app, implement WebSocket or Polling here
                throw new Error("Stream is generating. Try again in a few minutes.");
            }
            throw new Error(data.message || "Failed to locate stream.");
        }

        setStatusMsg("Manifest received. Initializing Shaka Player...");

        // 2. Initialize Shaka Player for HLS/DASH Support with Adaptive Bitrate
        shaka.polyfill.installAll();
        if (!shaka.Player.isBrowserSupported()) {
          throw new Error('Browser not supported for advanced streaming.');
        }

        player = new shaka.Player(videoRef.current);
        ui = new shaka.ui.Overlay(player, containerRef.current, videoRef.current);
        
        // Configure Adaptive Bitrate (ABS) and UI Elements
        ui.configure({
            controlPanelElements: [
                'play_pause', 'time_and_duration', 'spacer', 
                'mute', 'volume', 'quality', 'fullscreen'
            ],
            addSeekBar: true
        });

        // Set DRM config if your backend encrypts the stream
        if (data.drm) {
            player.configure({
                drm: { servers: { 'com.widevine.alpha': data.drm.licenseServer } }
            });
        }

        // 3. Load the Adaptive Bitrate Manifest (.m3u8 or .mpd) generated by FFmpeg
        await player.load(data.manifestUrl);
        
        if (isMounted) {
            setPlayerInstance(player);
            setIsFetching(false);
            videoRef.current.play().catch(() => console.log("Autoplay blocked."));
        }

      } catch (err) {
        if (isMounted) {
            setError(err.message);
            setIsFetching(false);
        }
      }
    };

    initializeStream();

    return () => {
      isMounted = false;
      if (ui) ui.destroy();
      if (player) player.destroy();
    };
  }, [tmdbId, mediaType, season, episode]);

  const handleClose = () => {
      if (playerInstance) playerInstance.destroy();
      navigate(-1);
  };

  if (isFetching) return (
      <div className="w-full h-screen bg-black flex flex-col items-center justify-center">
          <Loader2 className="w-14 h-14 animate-spin text-[#00A8E1] mb-4" />
          <div className="text-[#B3B3B3] text-sm font-bold tracking-widest uppercase">{statusMsg}</div>
      </div>
  );

  if (error) return (
      <div className="w-full h-screen bg-black flex flex-col items-center justify-center text-white">
          <p className="text-xl mb-4 font-bold text-red-500">{error}</p>
          <button onClick={handleClose} className="px-6 py-2 bg-[#00A8E1] rounded">Go Back</button>
      </div>
  );

  return (
    <div className="relative w-full h-screen bg-black overflow-hidden select-none">
        {/* Header Overlay */}
        <div className="absolute top-0 left-0 w-full p-6 bg-gradient-to-b from-black/80 to-transparent z-50 flex justify-between items-center pointer-events-none">
            <div className="text-white drop-shadow-md pointer-events-auto">
                <h1 className="text-2xl font-bold">{title}</h1>
                {mediaType === 'tv' && <p className="text-sm opacity-80">Season {season}, Ep. {episode}</p>}
            </div>
            <button onClick={handleClose} className="text-white hover:text-[#00A8E1] pointer-events-auto transition p-2">
                <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>
            </button>
        </div>

        {/* Shaka Player Container */}
        <div ref={containerRef} className="w-full h-full">
            <video ref={videoRef} className="w-full h-full object-contain bg-black" playsInline />
        </div>
    </div>
  );
};

export default PrimePlayer;
